### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by ale-rt** [collective/collective.vdexvocabulary#12]
We just merged the Python3 branch, it would be great to have a release.

**Comment by ale-rt** [comment]
@agitator I think you have the rights to submit a new release on PyPI. Can you do that?
Or if you want you can share the permissions to me or Johannes and we can do that.

**Comment by lukasgraf** [comment]
@ale-rt I created a [0.3 release](https://pypi.org/project/collective.vdexvocabulary/0.3/) and added you and @thet as maintainers on PyPi.

**Comment by ale-rt** [comment]
Thanks a lot!
