### ISSUE TITLE
Create a 0.2.1 release

### ISSUE THREAD

**Issue by lukasgraf** [collective/collective.vdexvocabulary#3]
Could someone that has the necessary permissions on PyPi please create a `0.2.1` release? I just merged #2 which is required for Plone 4.3 compatibility.

**Comment by garbas** [comment]
> Assigned #3 to @garbas.

i'm not mantaining this anymore. ping nutjob, regebro or hpeteragitator. or
i can also give away permissions on pypi.

## 

Rok Garbas - http://www.garbas.si

**Comment by lukasgraf** [comment]
@garbas I see, thanks for the quick response anyway.

So @nutjob4life, @regebro or @agitator, would any of you mind cutting a release?

I'd also be happy to do it myself if anyone can at me to the package index maintainers on PyPi (though I'd be using `zest.releaser` and would apply the necessary changes first, like extracting the change log into a separate file).

**Comment by lukasgraf** [comment]
Thanks @agitator for adding me on PyPi. I just created a `0.2.1` release.

/cc @ale-rt

**Comment by ale-rt** [comment]
## Great!

Alessandro Pisa - RedTurtle Technology
E-mail: alessandro.pisa@redturtle.it
Web Site: http://www.redturtle.it
Phone: +39 0532 1915958
